version: "3.8"
name: hello-auth
services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.2
    ports:
      - "21081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-import.json:ro
    command:
      - start-dev
      - --import-realm

